### ISSUE TITLE
Results card tabs collapsed

### ISSUE THREAD

**Issue by p1lh4** [marcokreeft87/formulaone-card#306] opened 2023-10-27 14:10 UTC
**Describe the bug**
After an update, the tabs on the result card appear truncated.

**To Reproduce**
Add a results card to the dashboard.

**Expected behavior**
Default style. If I edit the dashboard the view returns to the default.
![Screenshot_2](https://github.com/marcokreeft87/formulaone-card/assets/7400002/5ee134f3-a254-4de7-a1b8-066faf0ceb41)

**Screenshots**
![Screenshot_1](https://github.com/marcokreeft87/formulaone-card/assets/7400002/0f6530a1-a87a-430f-9ccc-ff4e371dd7dd)

**Additional context**
Card version 1.8.8
HA 2023.10

Truncated tabs

```
        <mwc-tab-bar>
    <!--?lit$433101553$--><!---->
                <mwc-tab hasimageicon=""><ha-icon slot="icon" icon="mdi:trophy"></ha-icon>
                </mwc-tab>
            <!----><!---->
                <mwc-tab hasimageicon=""><ha-icon slot="icon" icon="mdi:timer-outline"></ha-icon>
                </mwc-tab>
            <!----><!---->
                <mwc-tab hasimageicon=""><ha-icon slot="icon" icon="mdi:flag-checkered"></ha-icon>
                </mwc-tab>
            <!---->                    
    </mwc-tab-bar>
```

Default tabs

```
<mwc-tab-bar>
	<!--?lit$433101553$--><!---->
		<mwc-tab hasimageicon="" dir="ltr" id="mdc-tab-1" active=""><ha-icon slot="icon" icon="mdi:trophy"></ha-icon>
		</mwc-tab>
	<!----><!---->
		<mwc-tab hasimageicon="" dir="ltr" id="mdc-tab-2"><ha-icon slot="icon" icon="mdi:timer-outline"></ha-icon>
		</mwc-tab>
	<!----><!---->
		<mwc-tab hasimageicon="" dir="ltr" id="mdc-tab-3"><ha-icon slot="icon" icon="mdi:flag-checkered"></ha-icon>
		</mwc-tab>
	<!---->                    
</mwc-tab-bar>
```

**Comment by marcokreeft87** [comment] 2023-10-27 14:18
Duplicate of [297](https://github.com/marcokreeft87/formulaone-card/issues/297) can you comment in that issue. I can't do anything about it. Seems to be something with the mwc-tab-bar sometimes doing weird stuff

**Closed by marcokreeft87** 2023-10-27 14:18 UTC
Labels: bug
