### ISSUE TITLE
Error: Please pass the correct sensor (races)

### ISSUE THREAD

**Issue by tcrnr1** [marcokreeft87/formulaone-card#44] opened 2022-12-30 21:25 UTC
card_type: next_race
sensor: sensor.formula_one_sensor_races
displayed ´Error: Please pass the correct sensor (races)´ after update to 0.2.1.
![Bildschirmfoto 2022-12-30 um 22 22 23](https://user-images.githubusercontent.com/79410488/210112646-44a96f18-3972-4079-8153-e796ff07f4a9.png)

**Comment by marcokreeft87** [comment] 2022-12-30 21:26
Duplicate of issue #33

**Closed** 2022-12-30 21:26 UTC
Labels: bug
